apiVersion: apps/v1
kind: Deployment
metadata:
  name: geometrix-ui
  namespace: geometrix
  labels:
    app: geometrix-ui
    version: "1.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geometrix-ui
  template:
    metadata:
      labels:
        app: geometrix-ui
    spec:
      containers:
        - name: geometrix-ui
          image: geometrix-ui:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
